apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai-services

bases:
  - ../../base

nameSuffix: -dev

commonLabels:
  environment: development

replicas:
  - name: ai-inference-service
    count: 1

patchesStrategicMerge:
  - replica-patch.yaml
  - resource-patch.yaml

configMapGenerator:
  - name: ai-inference-config
    behavior: merge
    literals:
      - LOG_LEVEL=DEBUG
