apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ai-inference-service.fullname" . }}
  labels:
    {{- include "ai-inference-service.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- toYaml .Values.config | nindent 4 }}
