{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "ai-inference-service.fullname" . }}
  labels:
    {{- include "ai-inference-service.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "ai-inference-service.selectorLabels" . | nindent 6 }}
{{- end }}
